-- password_reset_tokens 테이블에 외래키 제약조건 추가
ALTER TABLE PASSWORD_RESET_TOKENS 
ADD CONSTRAINT FK_PASSWORD_RESET_TOKENS_CANDIDATE 
FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATES(CANDIDATE_ID);

-- 인덱스 생성 (성능 향상을 위해)
CREATE INDEX IDX_PASSWORD_RESET_TOKENS_CANDIDATE_ID ON PASSWORD_RESET_TOKENS(CANDIDATE_ID);
CREATE INDEX IDX_PASSWORD_RESET_TOKENS_EXPIRATION_DATE ON PASSWORD_RESET_TOKENS(EXPIRATION_DATE); 